Make.create(name: "Proton")
Make.create(name: "Produa")
Make.create(name: "Toyota")
Make.create(name: "Honda")
Make.create(name: "Ford")
Make.create(name: "Nissan")
Make.create(name: "BMW")
Make.create(name: "Isuzu")
Make.create(name: "Mercedes-Benz")


Model.create(name: "Wira", make_id: Make.find_by(name: "Proton").id)
Model.create(name: "Satria", make_id: Make.find_by(name: "Proton").id)
Model.create(name: "Saga", make_id: Make.find_by(name: "Proton").id)
Model.create(name: "Arena", make_id: Make.find_by(name: "Proton").id)
Model.create(name: "Exora", make_id: Make.find_by(name: "Proton").id)
Model.create(name: "Gen2", make_id: Make.find_by(name: "Proton").id)
Model.create(name: "Inspira", make_id: Make.find_by(name: "Proton").id)
Model.create(name: "Iriz", make_id: Make.find_by(name: "Proton").id)
Model.create(name: "Iswara", make_id: Make.find_by(name: "Proton").id)
Model.create(name: "Juara", make_id: Make.find_by(name: "Proton").id)
Model.create(name: "Perdana", make_id: Make.find_by(name: "Proton").id)
Model.create(name: "Persona", make_id: Make.find_by(name: "Proton").id)
Model.create(name: "Preve", make_id: Make.find_by(name: "Proton").id)
Model.create(name: "Putra", make_id: Make.find_by(name: "Proton").id)
Model.create(name: "Savvy", make_id: Make.find_by(name: "Proton").id)
Model.create(name: "Suprima", make_id: Make.find_by(name: "Proton").id)
Model.create(name: "Waja", make_id: Make.find_by(name: "Proton").id)

Model.create(name: "Myvi", make_id: Make.find_by(name: "Produa").id)
Model.create(name: "Alza", make_id: Make.find_by(name: "Produa").id)
Model.create(name: "Axia", make_id: Make.find_by(name: "Produa").id)
Model.create(name: "Viva", make_id: Make.find_by(name: "Produa").id)
Model.create(name: "Bezza", make_id: Make.find_by(name: "Produa").id)
Model.create(name: "Kelisa", make_id: Make.find_by(name: "Produa").id)
Model.create(name: "Kenari", make_id: Make.find_by(name: "Produa").id)
Model.create(name: "Kancil", make_id: Make.find_by(name: "Produa").id)

Package.create(name: "Local Cars | Semi - Synthetics RM 149")
Package.create(name: "Local Cars | Fully - Synthetics RM 209")
Package.create(name: "Produa Axia Model | Request Quote")
Package.create(name: "Others | Request Quote")

