Make.create(name: "Proton")
Make.create(name: "Produa")
Make.create(name: "Toyota")
Make.create(name: "Honda")
Make.create(name: "Ford")
Make.create(name: "Nissan")
Make.create(name: "BMW")
Make.create(name: "Isuzu")
Make.create(name: "Mercedes-Benz")

Model.create(name: "Wira", make_id: 1)
Model.create(name: "Satria", make_id: 1)
Model.create(name: "Saga", make_id: 1)
Model.create(name: "Arena", make_id: 1)
Model.create(name: "Exora", make_id: 1)
Model.create(name: "Gen2", make_id: 1)
Model.create(name: "Inspira", make_id: 1)
Model.create(name: "Iriz", make_id: 1)
Model.create(name: "Iswara", make_id: 1)
Model.create(name: "Juara", make_id: 1)
Model.create(name: "Perdana", make_id: 1)
Model.create(name: "Persona", make_id: 1)
Model.create(name: "Preve", make_id: 1)
Model.create(name: "Putra", make_id: 1)
Model.create(name: "Savvy", make_id: 1)
Model.create(name: "Suprima", make_id: 1)
Model.create(name: "Waja", make_id: 1)
Model.create(name: "Myvi", make_id: 2)
Model.create(name: "Alza", make_id: 2)
Model.create(name: "Axia", make_id: 2)
Model.create(name: "Viva", make_id: 2)
Model.create(name: "Bezza", make_id: 2)
Model.create(name: "Kelisa", make_id: 2)
Model.create(name: "Kenari", make_id: 2)
Model.create(name: "Kancil", make_id: 2)

Package.create(name: "Please select a package")
Package.create(name: "Local Cars | Semi - Synthetics RM 149")
Package.create(name: "Local Cars | Fully - Synthetics RM 209")
Package.create(name: "Produa Axia Model | Request Quote")
Package.create(name: "Others | Request Quote")

Mjloc.create(name: "Putrajaya")
Mjloc.create(name: "Cyberjaya")
Mjloc.create(name: "Klang Valley")
Mjloc.create(name: "Kuantan")

Mnloc.create(name: "Precint 1", mjloc_id: 1)
